// <auto-generated />
namespace ERPDAL.AgricultureContextMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class RM_suppadd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RM_suppadd));
        
        string IMigrationMetadata.Id
        {
            get { return "202210171042183_RM_suppadd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
