// <auto-generated />
namespace ERPDAL.AgricultureContextMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class stokistidaddretursale : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(stokistidaddretursale));
        
        string IMigrationMetadata.Id
        {
            get { return "202211080813337_stokistidaddretursale"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
