// <auto-generated />
namespace ERPDAL.AgricultureContextMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
<<<<<<<< HEAD:ERPDAL/AgricultureContextMigrations/202210261053414_Agriculture_Agriculture.Designer.cs
    public sealed partial class Agriculture_Agriculture : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Agriculture_Agriculture));
        
        string IMigrationMetadata.Id
        {
            get { return "202210261053414_Agriculture_Agriculture"; }
========
    public sealed partial class Agriculture_AgroProductSales : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Agriculture_AgroProductSales));
        
        string IMigrationMetadata.Id
        {
            get { return "202210260847297_Agriculture_AgroProductSales"; }
>>>>>>>> 1c7cd6a79ecc6de6083f7a9f42ee72d550625be4:ERPDAL/AgricultureContextMigrations/202210260847297_Agriculture_AgroProductSales.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
