// <auto-generated />
namespace ERPDAL.AgricultureContextMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Agriculture_SelesStatus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Agriculture_SelesStatus));
        
        string IMigrationMetadata.Id
        {
            get { return "202211210730445_Agriculture_SelesStatus"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
