// <auto-generated />
namespace ERPDAL.AgricultureContextMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Rawmissuedetailstableup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Rawmissuedetailstableup));
        
        string IMigrationMetadata.Id
        {
            get { return "202210230541244_Rawm issue details tableup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
