// <auto-generated />
namespace ERPDAL.ControlPanelContextMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ControlPanel_BranchAddress : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ControlPanel_BranchAddress));
        
        string IMigrationMetadata.Id
        {
            get { return "202008050953442_ControlPanel_BranchAddress"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
